cloudOrchestration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path(r'', include('launchApp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentification.urls')),
    path('graph/', include('graphGenerator.urls')),
    path('node/', include('nodePerso.urls')),
    path('template/', include('createTemplate.urls')),
    path('qos/', include('qos.urls')),
     # logout default function
    url(r'^logout/', auth_views.logout, {'next_page': 'launchApp:home'}, name='logout'),
]


#load the static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

createTemplate/urls.py
from django.conf.urls import url
from . import views

app_name = 'createTemplate' #creer un namespace


urlpatterns = [

    url(r'^listNode/$', views.list, name='list'),
    url(r'^generateForm/$', views.form, name='templateForm'),
    #url(r'^validateForm/$', views.validateForm, name='validateForm'),
    url(r'^loadDist/$', views.loadDist, name='loadDist'),
    url(r'^validateForm/$', views.formGen, name='formGen'),
    url(r'^validateFormRel/$', views.formRel, name='formRel'),

]

qos/urls.py
from django.conf.urls import url
from . import views

app_name = 'qos' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.list, name='list'),
    url(r'^calcul/$', views.calcul, name='calcul'),
    
]

createTemplate/views.py
from _sitebuiltins import _Printer
from django.http import Http404
from django.shortcuts import render
from django.http import HttpResponse
from django.views.decorators.csrf import csrf_exempt
from django.forms import formset_factory
from .forms import *
from nodePerso.models import *
import json,os
from django.forms import inlineformset_factory


from functools import partial, wraps
from django.forms.formsets import formset_factory


BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))


@csrf_exempt
def list(request):
    nodes = dict()
    for baseNode in NodePersonalised.BaseNodes:
        nodes.update({baseNode[1] : baseNode[0] })
    for persoNode in request.user.nodepersonalised_set.all():
        nodes.update({persoNode.name: 'p' + str(persoNode.pk)})
    json_data = json.dumps(nodes)
    return HttpResponse(json_data, content_type="application/json")


        

@csrf_exempt
def loadDist(request):
    windowsDistribution = {"windowsXp" : "Windows Xp", "windows7" :"Windows 7", "windows10" :"Windows 10"}
    linuxDistribution = {"ubuntu" : "Ubuntu", "mint" :"Mint"}
    if(request.POST["type"] == "windows"):
        distribution = windowsDistribution
    else:
        distribution = linuxDistribution
    json_data = json.dumps(distribution)
    return HttpResponse(json_data, content_type="application/json")

def form(request):
    formset = None
    templateSpecification = request.POST.copy()
    del templateSpecification['csrfmiddlewaretoken']   
    for element in request.POST:
        if(request.POST[element] == "Compute"):
            formset = formset_factory(ComputeForm , extra=int(request.POST["num1"]))
        if("node" in element):
            nodeType = request.POST[element]
            number = request.POST["num"+element.replace("node","")]
            del templateSpecification[element]
            del templateSpecification["num"+element.replace("node","")]
            templateSpecification.update({nodeType:number,'current':'Compute','templateName':request.POST['templateName']})
    request.session['templateSpecification'] = templateSpecification
    forms = formset()
    return render(request, 'createTemplate/form.html', {'form': forms,'templateName':templateSpecification['templateName'],"type":"Compute"})

        #formset = formset_factory(ComputeForm)
        #forms = formset(request.POST,prefix='form')
        

        #for form in request.POST:
         #   print(form)
        #print(form)
        #del request.session['templateSpecification']



def formGen(request):
    formset = None
    suiv = None
    typeObj = None
    perso = None
    if 'templateSpecification' in request.session:
        templateSpecification = request.session['templateSpecification']
        current = templateSpecification['current']
        data = request.POST.copy()
        del data['csrfmiddlewaretoken'] 
        #controle sur le chargement du meme formulaire
        if "previous" in templateSpecification:
            previous = templateSpecification["previous"]
            if (templateSpecification[previous] == data):
                raise Http404("Chargement")
        #end controle 

        aux,formset = genFormset(current,templateSpecification)
        forms = formset(request.POST)
        if(forms.is_valid()):

            ##### enregisterer data dans la session
            inst = dict()
            cpt = 1
            for form in forms:
                if form.is_valid():
                    form = form.cleaned_data
                    if (current == "Compute" or current == "database" or current == "dbms" or current == "softwareComponent" or current == "webApplication" or current == "webServer"):
                        node = dict()
                        for field in form:
                            node.update({field:form[field]})
                        key = str(cpt)
                        inst.update({key:node })
                        cpt += 1;
                    else:
                        perso = NodePersonalised.objects.get(pk = current.replace("p",""))
                        #print(perso)
                        persoAtt = dict()
                        nodeBase =  dict()
                        aux = 0;
                        # contruire dict contenant les attributs perso
                        for attribute in perso.persoattribute_set.all():
                            for field in form:
                                if field == attribute.name:
                                    aux = aux+1
                                    persoAtt.update({aux:{field:form[field],'id':attribute.pk}})
                        for persoa in persoAtt.values():
                            for element in persoa:
                                if element != 'id':
                                    del form[element]
                            #persoAtt.update({'id':attribute.pk})
                        # contruire dict contenant les attributs du nodeBase
                        for field in form:
                            nodeBase.update({field:form[field]})
                        key = str(cpt)

                        inst.update({key:{"nodeBase": nodeBase,"persoAtt":persoAtt}})
                        cpt += 1;
                    templateSpecification[current]=inst
            #####

             # chercher la node suivante
            for node in templateSpecification:
                if (node != "templateName" and node != "current" and node != "previous" and not isinstance(templateSpecification[node],dict)):
                    suiv = node 

            # tester la fin des nodes
            if suiv is None: # si fin generer formulaire des relations
                #del request.session['templateSpecification']
                formulaire = ""
                del templateSpecification['current']
                if 'previous' in templateSpecification:
                    del templateSpecification['previous']
                for nodeType in request.session['templateSpecification']:
                    options=""
                    if nodeType != 'Compute' and nodeType != 'templateName':    
                        if nodeType in ["database","dbms","softwareComponent","webServer","webApplication"]:
                            formulaire += relationForm(nodeType,request)
                        else: # cas des nodes perso
                            node = NodePersonalised.objects.get(pk = nodeType.replace("p",""))
                            information = request.session['templateSpecification'][nodeType].values()
                            base = str(node.derivedFrom)
                            formulaire += relationFormPerso(base,request,nodeType)
                #del templateSpecification['current']
                #del templateSpecification['previous'] 
                if formulaire == "":
                    path = os.path.join(BASE_DIR, "userData/"+str(request.user.pk))
                    template = saveData(templateSpecification,path,None)
                    if not os.path.exists(path):
                        os.makedirs(path)
                    with open(os.path.join(path, "test.yaml"), 'w') as source:
                        source.write(template)
                    return render(request, 'graphGenerator/att.html', {'path': str(request.user.pk)+'/test.yaml'})
                request.session['templateSpecification'] = request.session['templateSpecification']
                return render(request, 'createTemplate/formRel.html', {'form': formulaire})
            #sinon dans le cas ou il existe plus de nodes
            else:
                templateSpecification['current'] = suiv
                templateSpecification['previous'] = current
                request.session['templateSpecification'] = templateSpecification
                typeNodeP,formset = genFormset(suiv,templateSpecification) 
                forms = formset()
                #typeNodeP = NodePersonalised.objects.get(pk = suiv.replace("p",""))
                return render(request, 'createTemplate/form.html', {'form': forms,'type':typeNodeP})
        else:
            return render(request, 'createTemplate/form.html', {'form': forms})
            
    else:
        raise Http404("Page does not exist")

def formRel(request):
    relationships = request.POST.copy()
    del relationships['csrfmiddlewaretoken']
    relationships = relationships.dict()
    templateSpecification = request.session['templateSpecification']
    path = os.path.join(BASE_DIR, "userData/"+str(request.user.pk))
    template = saveData(templateSpecification,path,relationships)
    if not os.path.exists(path):
        os.makedirs(path)
    with open(os.path.join(path, "test.yaml"), 'w') as source:
        source.write(template)
    return render(request, 'graphGenerator/att.html', {'path': str(request.user.pk)+'/test.yaml'})
    #raise Http404("Page does exist")

def genFormset(current,templateSpecification):
    #controle data
    typeNodeP = current
    print('curr: '+current)
    print('val: '+str(templateSpecification))
    if(current == "Compute"):
        formset = formset_factory(ComputeForm,extra= int(templateSpecification[current]))
    elif(current == "database"):
        formset = formset_factory(DatabaseForm,extra= int(templateSpecification[current]))
    elif (current == "dbms"):
        formset = formset_factory(DbmsForm,extra= int(templateSpecification[current]))
    elif (current == "softwareComponent"):
        formset = formset_factory(SoftwareComponentForm,extra= int(templateSpecification[current]))
    elif (current == "webApplication"):
        formset = formset_factory(WebApplicationForm,extra= int(templateSpecification[current]))
    elif (current == "webServer"):
        formset = formset_factory(WebServerForm,extra= int(templateSpecification[current]))
    else:
        perso = NodePersonalised.objects.get(pk = current.replace("p",""))
        typeNodeP = perso.name

createTemplate/templates/createTemplate/form.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} Create Template {% endblock %}

{% block mylink %}


	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="assets/img/favicon.png" />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
	<link href="{% static 'template/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'template/assets/css/material-bootstrap-wizard.css' %}" rel="stylesheet" />

		<!--   Core JS Files   -->
	<script src="{% static 'template/assets/js/jquery-2.2.4.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'template/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'template/assets/js/jquery.bootstrap.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="{% static 'template/assets/js/material-bootstrap-wizard.js' %}"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="{% static 'template/assets/js/jquery.validate.min.js' %}"></script>
	<style type="text/css">
		.errorlist{
			color: red;
		}
		.test{
			background-image: url("{% static 'media/images/test2.jpg' %}");
		}
	</style>
{% endblock %}


{% block mybody%}
	<div class="test"style="background-color:#F5F5F5">
	    <!--   Big container   -->
	    <div class="container" >
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">
		            <!--      Wizard container        -->
		            <div class="wizard-container">
		                <div class="card wizard-card" data-color="red" id="wizard">
		                    <form class="form-horizontal" role="form" action="{% url 'createTemplate:formGen' %}" method="post">
		                    	{% csrf_token %}
		                    	{{ form.management_form }}
		                <!--        You can switch " data-color="blue" "  with one of the next bright colors: "green", "orange", "red", "purple"             -->

		                    	<div class="wizard-header">
		                        	<h3 class="wizard-title">
		                        		{{type}}
		                        	</h3>
									<h5>{{ templateName }}</h5>
		                    	</div>
								<div class="wizard-navigation">
									<ul>
										{% for field in form %}
			                            	<li>
			                            		<a href="#instance{{ forloop.counter }}" data-toggle="tab">
			                            			Instance {{ forloop.counter }}
			                            		</a>
			                            	</li>
			                            {% endfor %}

			                        </ul>
								</div>

		                        <div class="tab-content">
							        {% for field in form %}
							        	<div class="tab-pane" id="instance{{forloop.counter}}">
                            				<div class="row">
							       			 	<div class="form-group has-errors text-danger small">
							        			</div>
							        			<div class="form-group row">
									   				<div class="col-sm-2 col-form-label">
									    				{{field.label_tag }}
									   				</div>
								    				<div class="col-sm-6">
									   					{{field }}
									    			</div>
												</div>
											</div>
                            			</div>
							        {% endfor %}
		                        </div>
	                        	<div class="wizard-footer">
	                            	<div class="pull-right">
	                                    <input type='button' class='btn btn-next btn-fill btn-danger btn-wd' name='next' value='Next' />
	                                    <button type='sumbit' class='btn btn-finish btn-fill btn-default btn-wd'>Sumbit</button>  
	                                </div>
	                                <div class="pull-left">
	                                    <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous' value='Previous' />
	                                </div>
	                                <div class="clearfix"></div>
	                        	</div>
		                    </form>
		                </div>
		            </div> <!-- wizard container -->
		        </div>
	    	</div> <!-- row -->
		</div> <!--  big container -->
		<br><br>
	</div>
</body>


	<script>
		var select = document.getElementById("os_type");
		var type = select.options[select.selectedIndex].value;
		$.ajax({
			type: "POST",
			url: "{% url 'createTemplate:loadDist'%}",
			dataType: "json",
			traditional: true,
			data: {"type":type},
			success: function(response) {
			    var distribution = document.getElementById ("distribution");
			    distribution.options.length = 0;
			    for (var value in response){
			    	distribution.options[distribution.options.length] = new Option (response[value], value);
			    }
                
			},
			error: function(response) {
				console.log(response);
			}
		})
		function loadDist()
		{
			var select = document.getElementById("os_type");
			var type = select.options[select.selectedIndex].value;
			$.ajax({
				type: "POST",
				url: "{% url 'createTemplate:loadDist'%}",
				dataType: "json",
				traditional: true,
				data: {"type":type},
				success: function(response) {
				    var distribution = document.getElementById ("distribution");
				    distribution.options.length = 0;
				    for (var value in response){
				    	distribution.options[distribution.options.length] = new Option (response[value], value);
				    }
                    
				},
				error: function(response) {
					console.log(response);
				}
			});
		}
    </script>
{% endblock %}

createTemplate/templates/createTemplate/formRel.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} Create Template {% endblock %}

{% block mylink %}


	<meta content='width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0' name='viewport' />
    <meta name="viewport" content="width=device-width" />

	<link rel="apple-touch-icon" sizes="76x76" href="assets/img/apple-icon.png" />
	<link rel="icon" type="image/png" href="assets/img/favicon.png" />

	<!--     Fonts and icons     -->
	<link rel="stylesheet" type="text/css" href="https://fonts.googleapis.com/css?family=Roboto:300,400,500,700|Roboto+Slab:400,700|Material+Icons" />
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />

	<!-- CSS Files -->
	<link href="{% static 'template/assets/css/bootstrap.min.css' %}" rel="stylesheet" />
	<link href="{% static 'template/assets/css/material-bootstrap-wizard.css' %}" rel="stylesheet" />

		<!--   Core JS Files   -->
	<script src="{% static 'template/assets/js/jquery-2.2.4.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'template/assets/js/bootstrap.min.js' %}" type="text/javascript"></script>
	<script src="{% static 'template/assets/js/jquery.bootstrap.js' %}" type="text/javascript"></script>

	<!--  Plugin for the Wizard -->
	<script src="{% static 'template/assets/js/material-bootstrap-wizard.js' %}"></script>

	<!--  More information about jquery.validate here: http://jqueryvalidation.org/	 -->
	<script src="{% static 'template/assets/js/jquery.validate.min.js' %}"></script>
	<style type="text/css">
		.errorlist{
			color: red;
		}
		label{
			margin-top: 10px;
		}
		.test{
			background-image: url("{% static 'media/images/test2.jpg' %}");
		}
		.card{
			margin-bottom: 50px;
		}
	</style>
{% endblock %}

{% block mybody%}
	<div class="test" style="background-color:#FFFFCC">
	    
	    <!--   Big container   -->
	    <div class="container">
	        <div class="row">
		        <div class="col-sm-8 col-sm-offset-2">
		            <!--      Wizard container        -->
		            <div class="wizard-container">
		                <div class="card wizard-card" data-color="red" id="wizard">
		                    <form class="form-horizontal" role="form" action="{% url 'createTemplate:formRel' %}" method="post">
		                    	{% csrf_token %}
		                <!--        You can switch " data-color="blue" "  with one of the next bright colors: "green", "orange", "red", "purple"             -->

		                    	<div class="wizard-header">
		                        	<h3 class="wizard-title">
		                        		Relations
		                        	</h3>
		                    	</div>
								<div class="wizard-navigation">
									<ul>
		                            	<li>
		                            		<a href="#" data-toggle="tab">
		                            			Relations
		                            		</a>
		                            	</li>

			                        </ul>
								</div>

		                        <div class="tab-content">
	                            	{{ form | safe}}
		                        </div>
	                        	<div class="wizard-footer">
	                            	<div class="pull-right">
	                                    <input type='button' class='btn btn-next btn-fill btn-danger btn-wd' name='next' value='Next' />
	                                    <button type='sumbit' class='btn btn-finish btn-fill btn-danger btn-wd'>Sumbit</button>  
	                                </div>
	                                <div class="pull-left">
	                                    <input type='button' class='btn btn-previous btn-fill btn-default btn-wd' name='previous' value='Previous' />
	                                </div>
	                                <div class="clearfix"></div>
	                        	</div>
		                    </form>
		                </div>
		            </div> <!-- wizard container -->
		        </div>
	    	</div> <!-- row -->
		</div> <!--  big container -->


{% endblock %}