cloudOrchestration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path(r'', include('launchApp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentification.urls')),
    path('graph/', include('graphGenerator.urls')),
    path('node/', include('nodePerso.urls')),
    path('template/', include('createTemplate.urls')),
    path('qos/', include('qos.urls')),
     # logout default function
    url(r'^logout/', auth_views.logout, {'next_page': 'launchApp:home'}, name='logout'),
]


#load the static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

nodePerso/urls.py
from django.conf.urls import url
from . import views

app_name = 'nodePerso' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.IndexView.as_view(), name='list'),
    url(r'^details/$', views.detailNode, name='detailNode'),
    url(r'^add/$', views.NodePCreate.as_view(), name='node-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.NodePUpdate.as_view(), name='node-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.NodePDelete.as_view(), name='node-delete'),

]

qos/urls.py
from django.conf.urls import url
from . import views

app_name = 'qos' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.list, name='list'),
    url(r'^calcul/$', views.calcul, name='calcul'),
    
]

nodePerso/models.py
from django.contrib.auth.models import User
from django.db import models
from django.urls import reverse
from datetime import date
from createTemplate.models import *
"""
class BaseNode(models.Model):

	name = models.CharField(max_length=250)
	type = models.CharField(max_length=250)
	date = models.DateField(("Date"), default=date.today)

	def __str__(self):
		return self.name
"""



class NodePersonalised(models.Model):

	BaseNodes = (('compute', 'Compute'),('database', 'Database'),('dbms', 'DBMS'),
		('softwareComponent', 'Software Component'),('webApplication', 'Web Application'),('webServer', 'Web Server'))
	name = models.CharField(max_length=250)
	date = models.DateField(("Date"), default=date.today)
	photo = models.FileField(default="img/serveur.jpg")
	derivedFrom = models.CharField(choices=BaseNodes,max_length=250,default="compute",verbose_name=u'Derived From')
	user = models.ForeignKey(User, default=1, on_delete=models.CASCADE)
	

	def get_absolute_url(self):
		return reverse('nodePerso:list')  #when i create user i give pk and return to this page
														#keyWordargs
	def __str__(self):
		return self.name

	def definition(self):
		derived =""
		if self.derivedFrom == "compute":
			derived = "tosca.nodes.Compute"
		elif self.derivedFrom == "database":
			derived = "tosca.nodes.Database"
		elif self.derivedFrom == "dbms":
			derived = "tosca.nodes.DBMS"
		elif self.derivedFrom == "softwareComponent":
			derived = "tosca.nodes.SoftwarComponent"
		elif self.derivedFrom == "webApplication":
			derived = "tosca.nodes.WebApplication"
		elif self.derivedFrom == "webServer":
			derived = "tosca.nodes.WebServer"

		definition = '''
  '''+self.name+''':
    derived_from: '''+derived

		if len(self.persoattribute_set.all())>0:
			definition += '''
    properties:'''
		typep= ''
		for perso in self.persoattribute_set.all():
			if perso.type == 'text':
				typep = 'string'
			else:
				typep = 'integer'
			definition += '''
      '''+perso.name+''':
        type: '''+typep
		return definition




class PersoAttribute(models.Model):

	type = models.CharField(max_length=250,default="text")
	name = models.CharField(max_length=250)
	node = models.ForeignKey(NodePersonalised, on_delete=models.CASCADE)

class PersoAttributeValue(models.Model):

	value = models.CharField(max_length=250)
	persoAtt = models.ForeignKey(PersoAttribute, on_delete=models.CASCADE)
	template = models.ForeignKey(Template, on_delete=models.CASCADE)

	def definition(self):
		definition = '''
        '''+self.persoAtt.name+''': '''+str(self.value)
		return definition

nodePerso/forms.py
from django import forms
from .models import NodePersonalised

#make a new user form class

#class UserForm(forms.ModelForm): # Model :blueprint to be used when making the forms
	
 	# password = forms.CharField(widget=forms.PasswordInput)

 	# class Meta:  # information about my class
 	# 	model = User  #whenever user sign in it goes to the same class
 	# 	fields = ['username', 'email' , 'password']

class NodePForm(forms.ModelForm):

    #my_model=forms.ModelChoiceField(queryset=BaseNode.objects.all(), widget=Select(attrs={'style':'background_color:#F5F8EC'}))


    class Meta:
        model = NodePersonalised
        fields = ['name', 'derivedFrom', 'photo']
        widgets = {
            'name': forms.TextInput(attrs={'class': 'input form-control', 'autofocus': True,
                                                'placeholder': 'Enter node name '}),
            'derivedFrom' : forms.Select(choices=NodePersonalised.BaseNodes,attrs={'class':'form-control'})
        }

nodePerso/views.py
from django.views import generic
from django.http import Http404
from django.views.generic.edit import CreateView , UpdateView , DeleteView #when i want to make a form form maj
from django.urls import reverse_lazy
from django.views.decorators.csrf import csrf_exempt
from django.http import HttpResponse
from django.core import serializers
import ast
import json
from .models import NodePersonalised,PersoAttribute
from .forms import NodePForm


class IndexView(generic.ListView):

    template_name = 'nodePerso/nodeslist.html'
    context_object_name = 'all_nodes'

    def get_queryset(self):  # get objects
        return self.request.user.nodepersonalised_set.all()

@csrf_exempt
def detailNode(request):

    try:
        node = NodePersonalised.objects.get(pk=request.POST["pk"])
        attributes = list(node.persoattribute_set.all())
    except NodePersonalised.DoesNotExist:
        raise Http404("Node does not exist")
    print(ast.literal_eval(serializers.serialize('json', [node]))[0])
    json_data = {'node': ast.literal_eval(serializers.serialize('json', [node]))[0],'base':str(node.derivedFrom)}
    data = dict()
    for attribute in attributes:
        data.update({str(attribute): ast.literal_eval(serializers.serialize('json', [attribute]))[0]})
    json_data.update({'attributes': data})
    json_data = json.dumps(json_data)
    return HttpResponse(json_data, content_type="application/json")


class NodePCreate(CreateView):
    form_class = NodePForm
    model = NodePersonalised

    def form_valid(self, form):
        node = form.save(commit=False)
        node.user = self.request.user
        node.save()
        attributes = self.request.POST.keys() - form.fields.keys() - {'csrfmiddlewaretoken'}
        for attribute in attributes:
            node.persoattribute_set.create(name=attribute, type=self.request.POST.get(attribute), node = node)    
        return super(NodePCreate, self).form_valid(form)


class NodePUpdate(UpdateView):
    form_class = NodePForm
    model = NodePersonalised

    def get(self, request, *args, **kwargs):
        self.object = self.get_object()
        form_class = self.get_form_class()
        form = self.get_form(form_class)
        attributes = list(self.object.persoattribute_set.all())
        return self.render_to_response(self.get_context_data(form=form, attributes=attributes))

    def form_valid(self, form):
        node = form.save()
        attributes = self.request.POST.keys() - form.fields.keys() - {'csrfmiddlewaretoken'}
        for attribute in attributes:
            if str(attribute).isdigit():
                att = PersoAttribute.objects.get(pk=attribute)
                att.type = self.request.POST.get(attribute)
                att.save()
            else:
                node.persoattribute_set.create(name=attribute, type=self.request.POST.get(attribute))
        return super(NodePUpdate, self).form_valid(form)


class NodePDelete(DeleteView):
    model = NodePersonalised
    success_url = reverse_lazy('nodePerso:list')

nodePerso/templates/nodePerso/form_template.html
<!--djanfo give you each field one by one  -->

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" style="font-size: 12px;">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

nodePerso/templates/nodePerso/nodepersonalised_form.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mytitle %}
{% if object %}
  Update Node 
{% else %}
  Add a new Node 
{% endif %}
{% endblock %}

{% block mylink %}
<link rel="stylesheet" href="{% static 'css/style_listnodes.css' %}">
<style type="text/css">
  .head h1{
    padding-top: 0px;
    text-shadow: 1px 1px 5px #610B38 ;
    color: #610B38
  }
  .panel{
    box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
  }
  .head{
    background-image: url("{% static 'media/images/test2.jpg' %}");
    padding-bottom: 100px;
  }
  .btPers{
    border-radius: 0px 10px 10px 0px;
  }
  .select{
    padding-right: 0px;
  }

</style>
{% endblock %}

{% block mybody%}
      <div class="head">
       <div class="container"  style="margin-left: 400px;margin-top: 50px;">
          <div class="row">
             <div class="container-fluid">
                <div class="row">
                   <div class="col-sm-12 col-md-6 col-md-offset-1">
                      <div class="panel panel-default">
                         <div class="panel-body">
                            {% if object %}
                              <center><h1>Update Node</h1></center>
                            {% else %}
                              <center><h1>Add a New Node</h1></center>
                            {% endif %}
                             
                             <center> <hr class="separator"> </center>
                            
                            <form class="form-horizontal" role="form" action="" method="post" enctype="multipart/form-data">
                               {% csrf_token %}   <!--  for common security practises-->
                               {% include 'nodePerso/form_template.html' %}  <!-- how we want our labels shown -->
                               <div id="attribut" class="row">
                                <a href="#" data-toggle="modal" data-target="#myModal" class=" pull-right"><span class="fa fa-plus" aria-hidden="true"> Add Attribute  </span></a>
                                </div>
                                <div class="form-group">
                                  <div class="col-sm-12">
                                     <!-- im pass 2 fields -->
                                     <center><button type="submit" class="btn btn-success"><i class="fa fa-check" aria-hidden="true"></i>&nbsp;Submit</button></center>
                                  </div>
                               </div>
                            </form>
                         </div>
                      </div>
                   </div>
                </div>
             </div>
          </div>
       </div><br>
      </div>
    <!-- Modal -->
    <div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
        <div class="modal-dialog" role="document">
            <div class="modal-content">
                <div class="modal-header">
                    <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                    <center> <h1 class="modal-title" id="myModalLabel">Add an attribute</h1> </center>
                </div>
                <div class="modal-body">
                    <div class="form-group">
                        <label class="control-label col-sm-4" for="nameAtt">Name of attribute :</label>
                        <div class="col-sm-4">
                            <input type="text" class="form-control" id="nameAtt" placeholder="">
                        </div>
                    </div><br>
                </div>
                <div class="modal-footer">
                   <center>
                    <button type="button" class="btn bt btn-primary" onclick="add()" data-dismiss="modal">Submit</button>
                    <button type="button" class="btn btn-primary" data-dismiss="modal">Close</button>
                   </center>
                </div>
            </div>
        </div>
    </div>

    <script>
        {% if attributes %}
            {% for attribute in attributes %}
                var div = document.createElement('div');
                var cpt = 1;
			    div.className = 'form-group';
			    div.id = cpt ;
			    div.innerHTML +=
							'<label class="control-label col-sm-2" for=""{{ attribute.pk }}"">{{ attribute.name }} : </label>\
							<div class="col-sm-4">\
							<select class="form-control select" id="{{ attribute.pk }}"  name="{{ attribute.pk }}">\
                                {% if attribute.type == "text" %}\
                                    <option value="text" selected >Text</option>\
                                    <option value="number" >Number</option>\
                                {% elif attribute.type == "number" %}\
                                    <option value="number" selected >Number</option>\
                                    <option value="text" >Text</option>\
                                {% endif %}\
                            </select>\
							</div>'
              {% if object %}
              {% else %}
                div.innerHTML += 
                '<div class="col-sm-4" style="margin-top: 50px;">\
                <a href="#" onclick="del('+ cpt +')" ><img src="{% static 'media/img/del.png' %}" width="20" height="20"></a>\
              </div>';
              {% endif %}
							
			    cpt = cpt + 1 ;
			document.getElementById('attribut').appendChild(div);
            {% endfor %}
        {% endif %}
        var cpt = 1;
		function add()
		{
			var div = document.createElement('div');
			div.className = 'form-group';
			div.id = cpt ;
			div.innerHTML =
							'<label class="control-label col-sm-2" for='+document.getElementById("nameAtt").value +'>'+document.getElementById("nameAtt").value +': </label>\
							<div class="col-sm-4 input-group">\
                                <select class="form-control select" id="'+document.getElementById("nameAtt").value +'" name="'+document.getElementById("nameAtt").value +'">\
                                    <option value="text">Text</option>\
                                    <option value="number">Number</option>\
                                </select>';
              {% if object %}
              {% else %}
                div.innerHTML += 
                '<span class="input-group-btn">\
                  <a href="#" onclick="del('+cpt+')" ><button class="btn btn-danger btn-add btPers" type="button">\
                      <span class="glyphicon glyphicon-minus"> \
                      </span>\
                  </button></a>\
              </span>\
              </div>';
              {% endif %}
			cpt = cpt + 1 ;
			document.getElementById('attribut').appendChild(div);
		}
		function del(id)
		{
			console.log(id);
			document.getElementById("attribut").removeChild(document.getElementById(id))
		}
	</script>

{% endblock %}

nodePerso/templates/nodePerso/nodeslist.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} NodesList {% endblock %}

{% block mylink %}
<link rel="stylesheet" href="{% static 'css/style_listnodes.css' %}">
<style type="text/css">
	.thumbnail{
		box-shadow: 0 4px 8px 0 rgba(0, 0, 0, 0.2), 0 6px 20px 0 rgba(0, 0, 0, 0.19);
	}
	.head{
		background-image: url("{% static 'media/images/test2.jpg' %}");
	}
</style>
{% endblock %}

{% block mybody%}
	<div class="head">
		<div class="container"  id="container-of-boxes">
			<button class="btn btn-lg btn-primary pull-right"  onclick="location.href = '{% url 'nodePerso:node-add' %}';">
				<i class="fa fa-plus-circle" ></i>
				Add a node
			</button>
			<div class="row">
				<center><h1> Your previous personalised nodes</h1></center>
				<center> <hr class="separator"> </center>
				
				<div class="albums-container container-fluid">
					<!-- Albums -->
					<div class="row">
						<div class="col-sm-12"></div>
						{% if all_nodes %}
							{% for node in all_nodes %}
								<div class="col-sm-2 col-lg-2"  id="box">
									<div class="thumbnail">
										<a href="" data-toggle="modal" data-target="#nodeDetail" onclick="loadNode({{ node.id }})">
											<img src="{{ node.photo.url }}" class="img-responsive  center-block">  <!-- {{ user.photo.url }} -->
										</a>
										<div class="caption">
											<div class="block-text rel zmin">
											<h2 class="text-center">{{ node.name }}</h2>
											</div>
											<!-- View Details -->
											<center><a href="" data-toggle="modal" data-target="#nodeDetail" onclick="loadNode({{ node.id }})" class="btn btn-primary btn-sm " role="button">
												View Details
											</a></center>
											<div>
											<center>
											<!-- Update Node -->
											<button type="button" class="btn btn-default upd btn-sm" title="Update" onclick="javascript:location.href='{% url 'nodePerso:node-update' node.id %}'" >
												<span class="fa fa-pencil-square-o" aria-hidden="true"></span>
											</button>
											<!-- Delete Node -->
											<form action="{% url 'nodePerso:node-delete' node.id %}" method="post" style="display: inline;">
												{% csrf_token %}
												<input type="hidden" name="album_id" value="{{ node.id }}"  title="Delete"/>
												<button type="submit" class="btn btn-default btn-sm"  title="Delete">
													<span class="glyphicon glyphicon-trash"></span>
												</button>
											</form>
											</center>
											</div>
										</div>
										
									</div>
								</div>
							{% endfor %}
						{% else %}
							<div class="col-sm-12">
								<br>
								<h1>No existing nodes </h1>
							</div>
					   {% endif %}
					</div>
				</div>
			</div>
		</div>
    </div>

    <!-- Modal -->
	<div class="modal fade" id="nodeDetail" tabindex="-1" role="dialog" aria-labelledby="nodeDetail">
		<div class="modal-dialog" role="document">
			<div class="modal-content">
				<div class="modal-header">
					<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                    <center><h2 class="modal-title" id="noeud"></h2></center>
				</div>
				<div class="modal-body" id="detailNode"> </div>
				<div class="modal-footer">
					<center><button type="button" class="btn btn-primary" data-dismiss="modal">Close</button></center>
				</div>
			</div>
		</div>
	</div>
	<script>
		function loadNode(pk)
		{
			$.ajax({
				type: "POST",
				url: "{% url 'nodePerso:detailNode'%}",
				dataType: "json",
				traditional: true,
				data: {"pk":pk},
				success: function(response) {
				    console.log(response);
				    var noeud = response.node.fields;
				    var attributes = response.attributes;
                    document.getElementById('noeud').innerHTML= 'Node: '+ noeud.name ;
                    document.getElementById('detailNode').innerHTML=
                        '   {% load static %}\
                            <center> \<center> \
                                <img src=" {% get_media_prefix %}'+ noeud.photo +'" class="img-responsive"> \
                            </center> \
                            <h4> Derived From : '+ response.base +'</h4> \
                            <h4> Date de creation :'+ noeud.date +'</h4> ';
                    for (var attribute in attributes){
                        console.log(attributes[attribute]);
                        document.getElementById('detailNode').innerHTML +=
                            '<h4>'+attributes[attribute].fields.name+' : '+ attributes[attribute].fields.type +'</h4>'
                    }
				},
				error: function(response) {
					console.log(response);
				}
			});
		}
    </script>
{% endblock %}