authentification/urls.py
from django.conf.urls import url
from . import views

app_name = 'authentification' #creer un namespace

urlpatterns = [

    url(r'^register$',views.UserFormView.as_view(), name='register'),
    url(r'^login$',views.login, name='login'),

    url(r'^users/$',views.IndexView.as_view() , name='users'), #im using a class but treat it as view
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view() , name='detail'), #pk for primary key because detal expects id
    url(r'^add/$', views.userCreate.as_view(), name='user-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.userUpdate.as_view(), name='user-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.userDelete.as_view(), name='user-delete'),

]

cloudOrchestration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path(r'', include('launchApp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentification.urls')),
    path('graph/', include('graphGenerator.urls')),
    path('node/', include('nodePerso.urls')),
    path('template/', include('createTemplate.urls')),
    path('qos/', include('qos.urls')),
     # logout default function
    url(r'^logout/', auth_views.logout, {'next_page': 'launchApp:home'}, name='logout'),
]


#load the static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

createTemplate/urls.py
from django.conf.urls import url
from . import views

app_name = 'createTemplate' #creer un namespace


urlpatterns = [

    url(r'^listNode/$', views.list, name='list'),
    url(r'^generateForm/$', views.form, name='templateForm'),
    #url(r'^validateForm/$', views.validateForm, name='validateForm'),
    url(r'^loadDist/$', views.loadDist, name='loadDist'),
    url(r'^validateForm/$', views.formGen, name='formGen'),
    url(r'^validateFormRel/$', views.formRel, name='formRel'),

]

graphGenerator/urls.py
from django.conf.urls import url
from . import views

app_name = 'grapheGenerator'

urlpatterns = [

    url(r'^form$', views.formu, name='postForm'),
    url(r'^graph$', views.renv, name='graph'),

]

nodePerso/urls.py
from django.conf.urls import url
from . import views

app_name = 'nodePerso' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.IndexView.as_view(), name='list'),
    url(r'^details/$', views.detailNode, name='detailNode'),
    url(r'^add/$', views.NodePCreate.as_view(), name='node-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.NodePUpdate.as_view(), name='node-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.NodePDelete.as_view(), name='node-delete'),

]

qos/urls.py
from django.conf.urls import url
from . import views

app_name = 'qos' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.list, name='list'),
    url(r'^calcul/$', views.calcul, name='calcul'),
    
]

authentification/models.py
from django.contrib.auth.models import Permission, User

authentification/forms.py
from django.contrib.auth.models import User  #basic user class
from django.contrib.auth.forms import UserCreationForm
from django import forms 
from django.core.exceptions import ValidationError

#make a new user form class

#class UserForm(forms.ModelForm): # Model :blueprint to be used when making the forms
	
 	# password = forms.CharField(widget=forms.PasswordInput)

 	# class Meta:  # information about my class
 	# 	model = User  #whenever user sign in it goes to the same class
 	# 	fields = ['username', 'email' , 'password']

class UserForm(forms.ModelForm):
    password = forms.CharField(widget=forms.PasswordInput(attrs={'class': 'input form-control','placeholder': 'Enter your Password'}))
    password2 = forms.CharField(label="Repeat password", 
    	widget=forms.PasswordInput(attrs={'class': 'input form-control','placeholder': 'Confirm your Password'}))
    name = forms.CharField(max_length=30
    	, widget=forms.TextInput(attrs={'class': 'input form-control','placeholder': 'Enter your Name'}) )
    email = forms.EmailField(
    widget=forms.EmailInput(attrs={'class': 'form-control','placeholder': 'Enter your Email'})
    )
    class Meta:
        model = User
        fields = ['username', 'email', 'name', 'password', 'password2']
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input form-control', 'autofocus': True , 
            	'placeholder': 'Enter your Username' })
        }

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password2'] != cd['password']:
            raise ValidationError("Password don't match")

        return cd['password2']


class SignUpForm(UserCreationForm):
    first_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    last_name = forms.CharField(max_length=30, required=False, help_text='Optional.')
    email = forms.EmailField(max_length=254, help_text='Required. Inform a valid email address.')

    class Meta:
        model = User
        fields = ('username', 'first_name', 'last_name', 'email', 'password1', 'password2', )

class UserUpdateForm(forms.ModelForm):

    #my_model=forms.ModelChoiceField(queryset=BaseNode.objects.all(), widget=Select(attrs={'style':'background_color:#F5F8EC'}))


    class Meta:
        model = User
        fields = [ 'username' , 'email' , 'password' ]  
        widgets = {
            'username': forms.TextInput(attrs={'class': 'input form-control', 'autofocus': True,
                                                'placeholder': ''}),
            'email': forms.EmailInput(attrs={'class': 'input form-control', 'autofocus': True,
                                                'placeholder': 'Please specify your email '}),
            'password': forms.PasswordInput(attrs={'class': 'input form-control', 'autofocus': True,
                                                'placeholder': 'Please enter your password'}),
        }

authentification/views.py
import os

from django.contrib.auth import authenticate
from django.contrib.auth import login as auth_login
from django.http import HttpResponseRedirect
from django.shortcuts import render, redirect, render_to_response
from django.template.context_processors import csrf
from django.urls import reverse
from django.views.generic import View

from .forms import UserForm
from django.contrib.auth.models import User
from django.views import generic
from django.http import Http404
from django.views.generic.edit import CreateView , UpdateView , DeleteView #when i want to make a form form maj
from django.urls import reverse_lazy
from .forms import *

# Create your views here.
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))



class Messages:
    success, info, warning, danger = range(4)
    def __init__(self,message, tag):
        self.message = message
        if tag == 0:
            self.tag = "alert alert-success"
        elif tag == 1:
            self.tag = "alert alert-info"
        elif tag == 2:
            self.tag = "alert alert-warning"
        else:
            self.tag = "alert alert-danger"





def login(request):

    if request.method == 'POST':
        username = request.POST['u']
        password = request.POST['p']
        user = authenticate(username=username, password=password)
        if user is not None:
            auth_login(request=request, user=user)
            return HttpResponseRedirect(reverse('launchApp:home'))
        else:
            msg_to_html = Messages('Invalid Credentials', Messages.danger)
            dictionary = dict(request=request, messages = msg_to_html)
            dictionary.update(csrf(request))
            return render_to_response('authentification/login.html', dictionary)
    elif request.method == 'GET':
        if request.user.is_authenticated is False:
            return render(request, 'authentification/login.html')
        else:
            return HttpResponseRedirect(reverse('launchApp:home'))




class UserFormView(View):
    form_class = UserForm
    template_name = 'authentification/register.html'

    def get(self,request):
        form = self.form_class(None)
        if request.user.is_authenticated is False:
            return render(request, self.template_name, {'form': form})  #to display blank form
        else:
            return HttpResponseRedirect(reverse('launchApp:home'))


    def post(self, request):  # if user clicks submit : process from data base
        form = self.form_class(
            request.POST)  # when clicks submit, all info data get stored in POST data to be passed to the form and the form valid the data

        if form.is_valid():  # store the info in data base but first make check validations
            user = form.save(
                commit=False)  # make a user object using whatever typed in the form but does not save it in data base
            # get cleaned (normalized) data : unifier la forme
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']

            # how to set user passwords , because they have h value
            user.set_password(password)
            user.save()  # put user in data base

            # returns User objects if credentials are correct
            user = authenticate(username=username, password=password)

            if user is not None:
                if user.is_active:  # compte banned by admin
                    auth_login(request, user)  # log the user in a session
                # now the user is loged in whatever the info i want i put request.user.username..
                # now redirect them to the home page
                return redirect('launchApp:home')

        return render(request, self.template_name, {'form': form})


# this def is if you want to change the user's password
def update_pwd(username, pwd):
    user_model = User.objects.get(username=username)
    user_model.set_password(pwd)
    user_model.save()

class IndexView(generic.ListView):
    
    template_name = 'authentification/userslist.html'  #when we get the list of all items put them in this template used
    form_class = UserForm
    context_object_name = 'all_users'  # because by default object_list
    def get_queryset(setf):  #get objects
        return User.objects.all()


class DetailView(generic.DetailView):
    
    model = User 
    form_class = UserForm
    template_name = 'authentification/detailuser.html' 

class userCreate (CreateView):

    form_class = UserForm
    template_name = 'authentification/register.html'

    def get(self,request):
        form = self.form_class(None)
        return render(request, self.template_name, {'form': form})  #to display blank form
        
    def post(self, request): 
        form = self.form_class(
            request.POST)  
        if form.is_valid():  
            user = form.save(commit=False)  
            username = form.cleaned_data['username']
            password = form.cleaned_data['password']
            user.set_password(password)
            user.save()  
            user = authenticate(username=username, password=password)

            if user is not None:
                return redirect('authentification:users')

        return render(request, self.template_name, {'form': form})


class userUpdate (UpdateView):
     model = User 
     form_class = UserUpdateForm 
      
     success_url = reverse_lazy('authentification:users')


class userDelete(DeleteView):
    model = User
    success_url = reverse_lazy('authentification:users')

    

authentification/templates/authentification/att.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mytitle %} MyGraph {% endblock %}

{% block mylink %}
	<link rel="stylesheet" href="{% static 'css/style_graph.css' %}">
	<script src="{% static 'cytoscape.js-master/dist/cytoscape.js' %}"></script>
	<script src="{% static 'ace-builds-master/src/ace.js' %}" type="text/javascript" charset="utf-8"></script>
	<script src="{% static 'ace-builds-master/src/mode-yaml.js' %}" type="text/javascript" charset="utf-8"></script>
{% endblock %}

{% block mybody%}
	{% if request.user.get_username %}
		<div id="header" class="header">
			<div class="container">
				<div class="row">
					<center><h3>Veuillez patienter SVP, vos fichiers sont en cours de traitement</h3></center>
				</div>
				<div class="row">
					<center><img src="{% static 'img/load.gif' %}" alt="Girl in a jacket"></center>
				</div>
			</div>
		</div>
		<form id="form" method="POST" action="{% url 'authentification:graph' %}" enctype="multipart/form-data">
			{% csrf_token %} 
			<input type="hidden" name="path" value="{{ path }}">
		</form>
		<script>
			window.setTimeout(function(){document.getElementById("form").submit();}, 5000);
		</script>
	{% endif %}
{% endblock %}

authentification/templates/authentification/detailuser.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} UsersList {% endblock %}

{% block mylink %}
<link rel="stylesheet" href="{% static 'css/style_graph.css' %}">
</style>
{% endblock %}

{% block mybody%}

 <div id="header" class="header">
    <div class="container"  >
    	<div class="row">
    		 <div class="col-sm-8 col-lg-4"  >
             
			<img src="{% static '/media/images/user.png' %}" class="img-responsive"/>  
			<h2>Username : {{user.username}}</h2>

			<h2>Email : {{user.email}}</h2>

			<h2>{{user.name}}</h2>


			{% if error_message %}  <!--une variable pour contenir le msg d'erreur-->
			     <p><strong>This is error message {{error_message}} </strong></p>
			{% endif %}
			</div>
			</div>
		</div>
	</div>
</div>


{% endblock %}

authentification/templates/authentification/form_template.html
<!--djanfo give you each field one by one  -->

{% for field in form %}
    <div class="form-group">
        <div class="col-sm-offset-2 col-sm-10">
            <span class="text-danger small">{{ field.errors }}</span>
        </div>
        <label class="control-label col-sm-2" style="font-size: 12px;">{{ field.label_tag }}</label>
        <div class="col-sm-10">{{ field }}</div>
    </div>
{% endfor %}

authentification/templates/authentification/login.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mytitle %} Login {% endblock %}

{% block mylink %}
    <link rel="stylesheet" href="{% static 'css/style_login.css' %}">
{% endblock %}

{% block mybody%}
	{% if request.user.get_username %}
		<div id="header" class="header">
			<div class="container">
				<div class="row">
					<br><br>
					<center> <h1> Welcome, {{ request.user.get_username }}</h1>  </center> 
					<center> <hr class="separator"> </center>
					<center> <h2>You are already connected </h2> </center>
				</div>
			</div>
		</div>
	{% else %}
		<div id="login" class="login">
			<div class="container">
				<div style="padding-top: 65px; padding-bottom: 35px;">
					{% if messages %}
						{% block messages %}
							<div class="container-fluid" align="center">
								<div class="{{ messages.tag }}" id="div_msg" align="center" role="alert"> {{ messages.message }}  </div>
							</div>
						{% endblock %}
					{% endif %}
				</div>
				<div class="row">
					<div id="loginbox"  class="col-md-4 col-md-offset-4">
						<div class="panel panel-default">
							<div style="color: blue; background-color: #FFFFCC;" class="panel-heading">
								<div class="panel-title"><center><h4>SIGN IN</h4></center></div>
							</div>     
							<div  style="padding-top:30px"  class="panel-body">
								<div style="display:none" id="login-alert" class="alert alert-danger col-sm-12"></div>
								<div id="div-forms">
									<!-- Begin # Login Form -->
									<form id="login-form" action="{% url 'authentification:login' %}" method="post" enctype="multipart/form-data"  role="form" >
										{% csrf_token %}
										<fieldset>
											<div class="form-group">
												<div style="margin-bottom: 25px" class="input-group">
													<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
													<input id="login-username" type="text" class="form-control" name="u" value="" placeholder="username or email">                                        
												</div>
												<div style="margin-bottom: 25px" class="input-group">
													<span class="input-group-addon"><i class="fa fa-lock fa-lg" aria-hidden="true"></i></span>
													<input id="login-password" type="password" class="form-control" name="p" placeholder="password">
												</div>
												<div class="input-group">
													<div class="checkbox">
														<label>
															<input id="login-remember" type="checkbox" name="remember" value="1"> Remember me
														</label>
														<span style="float:right; margin-left: 100px;"> 
															<a  href="#"  onClick="$('#loginbox').hide(); $('#passwordbox').show()"> Forgot password? </a>
														</span>
													</div>
												</div>
												<div style="margin-top:10px" class="form-group"></div>
											</div>
											<input class="btn btn-lg btn-success btn-block" type="submit" value="Login">
										</fieldset>
									</form>
									<center><h4>OR</h4></center>
									<input class="btn btn-lg btn-primary btn-block" type="submit" value="Login via facebook">
									<div class="form-group">
										<div class="col-md-12 control">
											<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
												Don't have an account! 
												<a href="#" onClick="location.href = '{% url 'authentification:register' %}';">
													Sign Up Here
												</a>
											</div>
										</div>
									</div>    
								</div>
							</div>
						</div>
						<div id="passwordbox" style="display:none; margin-top:100px;" class="col-md-4 col-md-offset-4">
							<div class="panel panel-default">
								<div style="color: blue; background-color: #FFFFCC;" class="panel-heading">
									<div class="panel-title"><center><h4>RESET PASSWORD</h4></center></div>
								</div>     
								<div  style="padding-top:50px"  class="panel-body">
									<div style="display:none" id="password-alert" class="alert alert-danger col-sm-12"></div>
									<form accept-charset="UTF-8" role="form">
										<fieldset>
											<div class="form-group">
												<div style="margin-bottom: 40px" class="input-group">
													<span class="input-group-addon"><i class="fa fa-user fa" aria-hidden="true"></i></span>
													<input id="mail" type="text" class="form-control" name="email" value="" placeholder="Enter your Email">                                        
												</div>
												<div style="margin-top:10px" class="form-group"> </div>
											</div>
											<input class="btn btn-lg btn-success btn-block" type="submit" value="Send">
										</fieldset>
									</form>
									<div class="form-group">
										<div class="col-md-12 control">
											<div style="border-top: 1px solid#888; padding-top:15px; font-size:85%" >
												Don't have an account! 
												<a href="#" onClick="location.href = '{% url 'authentification:register' %}';">
													Sign Up Here
												</a>
											</div>
										</div>
									</div>    
								</div>
							</div>
						</div>
					</div>
				</div>
				<br><br><br><br><br><br><br><br>
			</div>
		</div>
	{% endif %}
	<script type="text/javascript">
		setTimeout(function () {
			$('#div_msg').fadeOut('fast');
		}, 5000);
	</script>
{% endblock %}

authentification/templates/authentification/nodeslist.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} NodesList {% endblock %}

{% block mylink %}
<link rel="stylesheet" href="{% static 'css/style_graph.css' %}">
{% endblock %}

{% block mybody%}
    <div id="header" class="header">
       <div class="container">

          <button class="btn btn-lg btn-primary"  onclick="location.href = '{% url 'authentification:node-add' %}';"><i class="fa fa-sign-in" ></i>  Add a node  </button>
          <div class="row">
             <h1> hello nodes are</h1>
             {% if all_nodes %}
             <ul>
                {% for node in all_nodes %}
                <li><a href="{% url 'authentification:detail' node.id %}">{{node.name }}</a></li>
                {% endfor %}
             </ul>
             {% else %}
             <h1>No nodes </h1>
             {% endif %}
             <div class="albums-container container-fluid">
                <!-- Albums -->
                <div class="row">
                   <div class="col-sm-12">
                      <!-- <h3>{{ user.username }}'s Albums</h3> -->
                   </div>
                   {% if all_nodes %}
                   {% for node in all_nodes %}
                   <div class="col-sm-4 col-lg-2">
                      <div class="thumbnail">

                         <a href="" data-toggle="modal" data-target="#nodeDetail" onclick="loadNode({{ node.id }})">
                            <img src="{{ node.photo.url }}" class="img-responsive">  <!-- {{ user.photo.url }} -->
                         </a>
                         <div class="caption">
                            <h2>{{ node.name }}</h2>
                            <h4>{{ node.typen }}</h4>
                            <!-- View Details -->
                            <a href="" data-toggle="modal" data-target="#nodeDetail" onclick="loadNode({{ node.id }})" class="btn btn-primary btn-sm" role="button">View Details</a>
                            <!-- Delete Album -->
                            
                            <form action="{% url 'authentification:node-update' node.id %}" method="get" style="display: inline;">
                               {% csrf_token %}
                               <input type="hidden" name="noe_id" value="{{ node.id }}"  title="Update"/>
                               <button type="submit" class="btn btn-default btn-sm" title="Update">
                               <span class="fa fa-pencil-square-o" aria-hidden="true"></span>
                               </button>
                            </form>

                            <form action="{% url 'authentification:node-delete' node.id %}" method="post" style="display: inline;">
                               {% csrf_token %}
                               <input type="hidden" name="album_id" value="{{ node.id }}"  title="Delete"/>
                               <button type="submit" class="btn btn-default btn-sm"  title="Delete">
                               <span class="glyphicon glyphicon-trash"></span>
                               </button>
                            </form>

                         </div>
                      </div>
                   </div>
                   {% endfor %}
                   {% else %}
                   <div class="col-sm-12">
                      <br>
                      <a href="{% url 'authentification:login'  %}">
                      <button type="button" class="btn btn-success">
                      <span class="glyphicon glyphicon-plus"></span>&nbsp; Add an Album
                      </button>
                      </a>
                   </div>
                   {% endif %}
                </div>
             </div>
          </div>
       </div>
    </div>

    <!-- Modal -->
		<div class="modal fade" id="nodeDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
			<div class="modal-dialog" role="document">
				<div class="modal-content">
					<div class="modal-header">
						<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
							<center> <h2 class="modal-title" id="nodeName"></h2>  </center>
					</div>
					<div class="modal-body" id="detailNode"> </div>
					<div class="modal-footer">
						<button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button>
					</div>
				</div>
			</div>
		</div>

    <script>
        function loadNode(pk)
		{
			$.ajax({
				type: "POST",
				url: "{% url 'authentification:detailNode'%}",
				dataType: "json",
				traditional: true,
				data: {"pk":pk},
				success: function(response) {
				    node = response[0]['fields'];
                    document.getElementById('nodeName').innerHTML= 'Node: '+ node.name
                    document.getElementById('detailNode').innerHTML=
                        '   {% load static %}\
                            <center> \
                                <img src=" {% get_media_prefix %}'+ node.photo +'" class="img-responsive"> \
                            </center> \
                            <h4> Type : '+ node.typen +'</h4> \
                            <h4> Attribute :'+ node.attribute +'</h4> \
                            <h4> Date de creation :'+ node.date +'</h4> '

					console.log(node);
				},
				error: function(response) {
					console.log(response);
				}
			});
		}
    </script>

{% endblock %}

authentification/templates/authentification/userslist.html
{% extends 'base.html' %}
{% load staticfiles %}

{% block mytitle %} UsersList {% endblock %}

{% block mylink %}
<link rel="stylesheet" href="{% static 'css/style_listnodes.css' %}">
</style>
{% endblock %}

{% block mybody%}

    <div id="header" class="header">
        <div class="container"  id="container-of-boxes">
            <button class="btn btn-lg btn-primary pull-right"  onclick="location.href = '{% url 'authentification:user-add'%}';">
                <i class="fa fa-plus-circle" ></i>
                Add user
            </button>
            <div class="row">
                <center><h1> The users are </h1></center>
                <center> <hr class="separator"> </center>
                
                <div class="albums-container container-fluid">
                    <!-- Albums -->
                    <div class="row">
                        <div class="col-sm-12"></div>
                        {% if all_users %}
                            {% for user in all_users %}
                                <div class="col-sm-4 col-lg-2"  id="box">
                                    <div class="thumbnail">
                                        <a href="{% url 'authentification:detail' user.id %}">
                                            <img src="{% static '/media/images/user.png' %}" class="img-responsive">  
                                        </a>
                                        
                                        <div class="caption">
                                            <center>
                                            <div class="block-text rel zmin">
                                            <h2 class="text-center">{{ user.username }}</h2>
                                            <h2 class="text-center">{{ user.name }}</h2>
                                            </div>
                                           </center>
                                            <!-- View Details -->
                                            <center>
                                                <a href="{% url 'authentification:detail' user.id  %}" class="btn btn-primary btn-sm" role="button">View Details</a>
                                            </center>
                                            <center>
                                             <!-- Update Album -->
                                            <form action="{% url 'authentification:user-update' user.id %}" method="get" style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="album_id" value="{{ user.id }}" />
                                                <button type="submit" title="user-update"  class="btn btn-default upd btn-sm">
                                                    <span class="fa fa-pencil-square-o" aria-hidden="true"></span>
                                                </button>
                                            </form>

                                            <!-- Delete Album -->
                                            <form action="{% url 'authentification:user-delete' user.id %}" method="post" style="display: inline;">
                                                {% csrf_token %}
                                                <input type="hidden" name="album_id" value="{{ user.id }}" />
                                                <button type="submit" class="btn btn-default btn-sm" title="user-delete">
                                                    <span class="glyphicon glyphicon-trash"></span>
                                                </button>
                                            </form>
                                            </center>
                                           
                                        </div>
                                        
                                    </div>
                                </div>
                            {% endfor %}
                        {% else %}
                            <div class="col-sm-12">
                                <br><br><br>
                                <br>
                                <h1>No existing users </h1>
                            </div>
                       {% endif %}
                    </div>
                </div>
            </div>
        </div>
    </div>
	
{% endblock %}