authentification/urls.py
from django.conf.urls import url
from . import views

app_name = 'authentification' #creer un namespace

urlpatterns = [

    url(r'^register$',views.UserFormView.as_view(), name='register'),
    url(r'^login$',views.login, name='login'),

    url(r'^users/$',views.IndexView.as_view() , name='users'), #im using a class but treat it as view
    url(r'^(?P<pk>[0-9]+)/$',views.DetailView.as_view() , name='detail'), #pk for primary key because detal expects id
    url(r'^add/$', views.userCreate.as_view(), name='user-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.userUpdate.as_view(), name='user-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.userDelete.as_view(), name='user-delete'),

]

cloudOrchestration/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views
from django.conf.urls import url
from django.views.generic import TemplateView

urlpatterns = [
    path(r'', include('launchApp.urls')),
    path('admin/', admin.site.urls),
    path('auth/', include('authentification.urls')),
    path('graph/', include('graphGenerator.urls')),
    path('node/', include('nodePerso.urls')),
    path('template/', include('createTemplate.urls')),
    path('qos/', include('qos.urls')),
     # logout default function
    url(r'^logout/', auth_views.logout, {'next_page': 'launchApp:home'}, name='logout'),
]


#load the static and media files
if settings.DEBUG:
    urlpatterns += static(settings.STATIC_URL , document_root = settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL , document_root = settings.MEDIA_ROOT)

createTemplate/urls.py
from django.conf.urls import url
from . import views

app_name = 'createTemplate' #creer un namespace


urlpatterns = [

    url(r'^listNode/$', views.list, name='list'),
    url(r'^generateForm/$', views.form, name='templateForm'),
    #url(r'^validateForm/$', views.validateForm, name='validateForm'),
    url(r'^loadDist/$', views.loadDist, name='loadDist'),
    url(r'^validateForm/$', views.formGen, name='formGen'),
    url(r'^validateFormRel/$', views.formRel, name='formRel'),

]

graphGenerator/urls.py
from django.conf.urls import url
from . import views

app_name = 'grapheGenerator'

urlpatterns = [

    url(r'^form$', views.formu, name='postForm'),
    url(r'^graph$', views.renv, name='graph'),

]

launchApp/urls.py
from django.conf.urls import url
from . import views


app_name = 'launchApp'

urlpatterns = [

    url(r'^$', views.home, name='home'),

]

nodePerso/urls.py
from django.conf.urls import url
from . import views

app_name = 'nodePerso' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.IndexView.as_view(), name='list'),
    url(r'^details/$', views.detailNode, name='detailNode'),
    url(r'^add/$', views.NodePCreate.as_view(), name='node-add'),
    url(r'^(?P<pk>[0-9]+)/update/$', views.NodePUpdate.as_view(), name='node-update'),
    url(r'^(?P<pk>[0-9]+)/delete/$', views.NodePDelete.as_view(), name='node-delete'),

]

qos/urls.py
from django.conf.urls import url
from . import views

app_name = 'qos' #creer un namespace


urlpatterns = [

    url(r'^list/$', views.list, name='list'),
    url(r'^calcul/$', views.calcul, name='calcul'),
    
]

launchApp/views.py
from django.shortcuts import render


def home(request):
    if request.user.is_authenticated is False:
        return render(request , 'launchApp/home.html')
    else:
        return render(request , 'launchApp/workspace.html')

launchApp/templates/launchApp/home.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mytitle %} CloudOrchestrator {% endblock %}

{% block mylink %}
	<link rel="stylesheet" href="{% static 'css/style_home.css' %}">
	<style type="text/css">
		.txt{
			margin-bottom: 100px;
		}
		.bt1{
			float: left;
    		margin-left: 300px;
		}
		.bt2{
			float: right;
    		margin-right: 300px;
		}
		.header button{
			margin-top: 100px;
		}
	</style>
{% endblock %}

{% block myitems%}
            <li class="nav-item">
				<a class="nav-link js-scroll-trigger"  href="#services"><span class="fa fa-server" aria-hidden="true"></span> 
					&nbsp;services
				</a>
			</li>
            <li class="nav-item">
				<a class="nav-link js-scroll-trigger"  href="#contact"><span class="fa fa-comments" aria-hidden="true"></span> 
					&nbsp;contact
				</a>
			</li>
{% endblock %}

{% block mybody%}
	<!--- Header -->
	<div id="header" class="header">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 col-md-12 ban  wow zoomIn"  data-wow-delay="1s">
					<div class="txt">
						<h1>Orchestration of cloud services</h1>
					</div>
					<button class="btn btn-lg btn-primary bt1"  onclick="location.href = '{% url 'authentification:login' %}';">
						<i class="fa fa-sign-in" ></i>Sign in  
					</button>
					<button class="btn btn-lg btn-success bt2"  onclick="location.href = '{% url 'authentification:register' %}';">
						<i class="fa fa-user-plus"></i>Join Now
					</button>
				</div>
			</div>
		</div>
	</div>
	<!-- End Header -->

	<!--- Description -->
	<section id="description" class="services">
		<div class="container">
			<div class="col-lg-12 tat">
				<h2 class="wow fadeInUp">Description</h2>
				<center> <hr class="separator"> </center>
			</div>
			<div class="row wow fadeInUp ">
				<p class="pg">
					Given its rapid growth, cloud computing is the new form of 21st century data storage. 
					It provides networked access to a shared pool of configurable computing resources. 
					These resources are characterized by elasticity, high availability, and reduced costs through the pay-per-use model. 
					This allows business processes to be run at a high level of performance and low cost of operation.
					<br>
					Operationalization of business processes on the cloud requires consistent coordination and precise understanding of a set of interacting cloud services. 
					These services are said orchestrated to satisfy the business process.
					<br>
					Cloud resource orchestration is about managing interactions between resources and automating business processes.
				</p>
			</div>
		</div>
	</section>
	<!-- End Description -->

	<!--- Services -->
	<section id="services" class="services">
		<div class="container">
			<div class="col-lg-12 tat">
				<h2 class="wow fadeInUp">At your service</h2>
				<center> <hr class="separator"> </center>
				<p class="wow fadeInUp" data-wow-delay="0.4">
					Our site offers you several services:
				</p>
			</div>
			<div class="row">
				<div class="col-lg-3 col-md-3 wow fadeInLeft" data-wow-delay="1.8s">
					<i class="fa fa-sort-alpha-desc" aria-hidden="true"></i>
					<h4>Orchestration of Cloud Services</h4>
					<p>Our site allows you to orchestrate cloud services of many types and even add new ones.</p>
				</div>
				<div class="col-lg-3 col-md-3 wow fadeInLeft" data-wow-delay="1.4s">
					<i class="fa fa-cloud-download" aria-hidden="true"></i>
					<h4>Evaluation of the orchestration plan</h4>
					<p> 
						We can evaluate the orchestration plan by calculating the overall estimated QoS of the plan and then the overall QoS of the plan and comparing the two
					</p>
				</div>
				<div class="col-lg-3 col-md-3 wow fadeInLeft" data-wow-delay="0.8s">
					<i class="fa fa-hourglass-start" aria-hidden="true"></i>
					<h4>Quality of service calculation</h4>
					<p>The application calculates the quality of services and uses it for evaluation. </p>
				</div>
				<div class="col-lg-3 col-md-3 wow fadeInLeft" data-wow-delay="0.4s">
					<i class="fa fa-clock-o" aria-hidden="true"></i>
					<h4>Adaptation of an orchestration plan</h4>
					<p>The application makes it possible to adapt an orchestration plan corresponding to users' needs. </p>
				</div>
			</div>
		</div>
	</section>
	<!-- End Services -->

	<!--- Portfolio -->
	<section id="portfolio" class="bg-light-gray">
		<div class="container">
			<div class="row">
				<div class="col-lg-12 text-center">
					<h2 class="section-heading wow fadeInDown">Album</h2>
					<center> <hr class="separator"> </center>
					<h3 class="section-subheading text-muted  wow fadeInDown">Here are some pictures from our gallery.</h3>
				</div>
			</div>
			<div class="row">
				<div class="col-md-4 col-sm-6 portfolio-item  wow rotateIn" data-wow-delay="0.4s">
					<a href="#portfolioModal1" class="portfolio-link" data-toggle="modal">
						<div class="portfolio-hover">
							<div class="portfolio-hover-content">
								<i class="fa fa-plus fa-3x"></i>
							</div>
						</div>
						<img src="{% static '/media/images/portfolio/petit/i1.PNG' %}" class="img-responsive" alt="">
					</a>
					<div class="portfolio-caption">
						<h4>Template creation</h4>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 portfolio-item wow rotateIn" data-wow-delay="0.4s">
					<a href="#portfolioModal2" class="portfolio-link" data-toggle="modal">
						<div class="portfolio-hover">
							<div class="portfolio-hover-content">
								<i class="fa fa-plus fa-3x"></i>
							</div>
						</div>
						<img src="{% static '/media/images/portfolio/petit/i3.jpg' %}" class="img-responsive" alt="">
					</a>
					<div class="portfolio-caption">
						<h4>Orchestartion plan Evaluation</h4>
					</div>
				</div>
				<div class="col-md-4 col-sm-6 portfolio-item wow rotateIn" data-wow-delay="0.4s">
					<a href="#portfolioModal3" class="portfolio-link" data-toggle="modal">
						<div class="portfolio-hover">
							<div class="portfolio-hover-content">
								<i class="fa fa-plus fa-3x"></i>
							</div>
						</div>
						<img src="{% static '/media/images/portfolio/petit/i2.jpg' %}" class="img-responsive" alt="">
					</a>
					<div class="portfolio-caption">
						<h4>Add cloud services</h4>
					</div>
				</div>
			</div>
		</div>
	</section>
	<!--- end Portfolio ---->

	<!-- Touch -->
	<div id="touch" class="touch">
		<div class="container">
			<div class="row">
				<h2 class="wow fadeInUp">Keep in touch with us</h2>
				<center> <hr class="separator1"> </center>
				<p class="wow fadeInUp" data-wow-delay="0.4s">
					You can stay in touch with us thanks to our different pages: 
				</p>
               <div class="col-lg-12 col-md-12 ">
					<a href="https://www.facebook.com/ENSI.tunisie/" title="Facebook" class="wow fadeInUp" data-wow-delay="0.6s">  <i class="social fa fa-facebook" aria-hidden="true"></i> </a>
					<a href="https://twitter.com/ensitn?lang=ar" title="Twitter" class="wow fadeInUp" data-wow-delay="0.8s">  <i class="social fa fa-twitter" aria-hidden="true"></i> </a>
					<a href="https://www.linkedin.com/school/11094564" title="Linkedin" class="wow fadeInUp" data-wow-delay="1s">  <i class="social fa fa-linkedin" aria-hidden="true"></i> </a>
					<a href="https://www.youtube.com/channel/UCjKdWF4JmIjUpS8YuPvnNzA" title="Youtube" class="wow fadeInUp" data-wow-delay="1.2s">  <i class="social fa fa-youtube" aria-hidden="true"></i> </a>
					<a href="https://github.com/OssecTN" title="Github" class="wow fadeInUp" data-wow-delay="1.4s">  <i class="social fa fa-github" aria-hidden="true"></i> </a><br>
				</div>
			</div>
		</div>
	</div>
	<!--- End touch ---->

	<!--- Contact ------>
	<div id="contact" class="contact">
		<div class="container">
			<div class="row">
				<h2 class="wow fadeInUp">Contact us</h2>
				<center> <hr class="separator"> </center>
				<p class="wow fadeInUp" data-wow-delay="0.4">
					You can contact us by filling in the following fields :
				</p>
				<div class="main  wow fadeInUp">
					<div class="info">Give Your Feedback!</div>
					<form action="mail_handler.php" method="post" name="form" class="form-box">
						<label for="name">Name</label><br>
						<input type="text" name="name" class="inp" placeholder="Veuillez saisir votre nom" required><br>
						<label for="email">Email</label><br>
						<input type="email" name="email" class="inp" placeholder="Veuillez saisir votre Email" required><br>
						<label for="phone">Phone</label><br>
						<input type="tel" name="phone" class="inp" placeholder="Veuillez saisir votre num tél" required><br>
						<label for="message">Message</label><br>
						<textarea name="msg" class="msg-box" placeholder="Veuillez saisir votre message ici..." required></textarea><br>
						<input type="submit" name="submit" value="Envoyer" class="sub-btn">
					</form>
				</div>
			</div>
		</div>
	</div>
	<!-- End Contact -->

	<!-- Portfolio Modal 1 -->
	<div class="portfolio-modal modal fade" id="portfolioModal1" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
			<div class="close-modal" data-dismiss="modal">
				<div class="lr">
					<div class="rl"></div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-lg-offset-2">
						<div class="modal-body">
							<!-- Project Details Go Here -->
							<h2>Template creation</h2>
							<img class="img-responsive" src="{% static '/media/images/portfolio/petit/i1.PNG' %}" alt="">
							<p>
								The application offers the possibility to create new template.
							</p>
							<center><button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer </button></center>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Portfolio Modal 2 -->
	<div class="portfolio-modal modal fade" id="portfolioModal2" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
			<div class="close-modal" data-dismiss="modal">
				<div class="lr">
					<div class="rl"></div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-lg-offset-2">
						<div class="modal-body">
							<h2>Evaluation plan of orchestartion</h2>
							<center><img class="img-responsive img-centered" src="{% static 'media/images/portfolio/petit/i3.jpg' %}" alt=""></center>
							<p>
								We can evaluate the orchestration plan by calculating the overall estimated QoS of the plan and then the overall QoS of the plan and comparing the two.
							</p>
							<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer </button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>

	<!-- Portfolio Modal 3 -->
	<div class="portfolio-modal modal fade" id="portfolioModal3" tabindex="-1" role="dialog" aria-hidden="true">
		<div class="modal-content">
			<div class="close-modal" data-dismiss="modal">
				<div class="lr">
					<div class="rl"></div>
				</div>
			</div>
			<div class="container">
				<div class="row">
					<div class="col-lg-8 col-lg-offset-2">
						<div class="modal-body">
							<!-- Project Details Go Here -->
							<h2>Add cloud services</h2>
							<center><img class="img-responsive img-centered" src="{% static '/media/images/portfolio/petit/i2.jpg' %}" alt=""></center>
							<p>The application makes it possible to add new cloud services corresponding to users' needs.</p>
							<button type="button" class="btn btn-primary" data-dismiss="modal"><i class="fa fa-times"></i> Fermer </button>
						</div>
					</div>
				</div>
			</div>
		</div>
	</div>
{% endblock %}

launchApp/templates/launchApp/workspace.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block mytitle %} MyWorkspace {% endblock %}
{% block mylink %}
	<link rel="stylesheet" href="{% static 'css/stylew.css' %}">
	<style type="text/css">
		.liMenu{
			width:100%;
		}
		.ulMenu{
			width: 100%;
		}
		.desc{
			color: white;
			font: 30px 'Cormorant Garamond';
		}
		.model-content{
			background-color: #F5F5F5;
		}
		.btPers{
			border-radius: 0px 10px 10px 0px;
		}
		.test{
			min-height: 400px;
		}
		.name{
			margin-top: 0px;
			padding-top: 0px;
		}
		.option{
			margin-top: 100px;
			padding-bottom: 100px;
			text-align: center;
		}
		.cloud{
			background-image: url(../media/images/cloud.png);
		    background-position: top;
		    background-repeat: no-repeat;
		    background-size: 100% 100%;
		    height: 150px;
		    width: 200px;
		    padding-top: 80px;
		}
		.option1{
			padding-right: 200px;
		}
		.option2{
			padding-left: 200px;
		}
	</style>
{% endblock %}

{% block mybody%}
	{% if request.user.get_username %}
		<div class="head">
			<div class="container">
				<div class="row">
					<div class="col-lg-12 col-md-12 ban  wow zoomIn"  data-wow-delay="1s">
						<div>
							<h1 class="name" >Welcome {{ request.user.get_username }} </h1>
							<br><br><br>
						</div>	
						
					</div>
				</div>
				<div class="row option">
					<div class="col-lg-6 col-md-6 wow fadeInLeft option1" data-wow-delay="0.2s">
						<li class="dropdown">
							<button href="#" class="btn btn-lg btn-info dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><i class="fa fa-sitemap" aria-hidden="true"></i>
								Model orchestration plan <span  id="lanBtnSel" class="caret"></span>
							</button>
							<ul class="dropdown-menu ulMenu" role="menu">
								<li class="liMenu">
									<a href="" data-toggle="modal" data-target="#createTemplate">With manually template creation </a>
								</li>
								<li class="liMenu">
									<a href="" data-toggle="modal" data-target="#myselectionModal">With prepared template </a>
								</li>
							</ul>
						</li>
					</div>
						<div class="col-lg-6 col-md-6 wow fadeInLeft" data-wow-delay="0.2s">
								<div class="row option2">
									
										<a href="{% url 'nodePerso:list' %}" class="" >
											<button href="#" class="btn btn-lg btn-info" aria-expanded="false"><i class="fa fa-sitemap" aria-hidden="true"></i>
												Manage your cutom node types
											</button>
										</a>
								</div>							
						</div>
				</div>	
			</div>
		</div>
		
		
		
		<!-- Modal Selection fichier -->
		<div class="modal fade" id="myselectionModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                        <center><h2 class="modal-title" >Create template</h2></center>
                    </div>
                    <form method="post" action="{% url 'grapheGenerator:postForm' %}" enctype="multipart/form-data">
                        {% csrf_token %}
                    <div class="modal-body" id="detailTemplate">
                        <h4>Template File Selection</h4>
								<div class="form-group">
									<div class="input-group input-file" name="toscaTemplate">
										<input type="text" class="form-control" placeholder='Choose a Template file...' />      
										<span class="input-group-btn">
											<button class="btn btn-default btn-choose" type="button">Choose</button>
										</span>
									</div>
								</div>
								<h4>TOSCA Definition File Selection</h4>
								<div class="form-group">
									<div class="input-group input-file" name="toscaDefinition">
										<input type="text" class="form-control" placeholder='Choose a TOSCA Definition file...' />
										<span class="input-group-btn">
											<button class="btn btn-default btn-choose" type="button">Choose</button>
										</span>
									</div>
								</div>
                        
                    </div>
                    <div class="modal-footer">
    	                <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-danger" data-dismiss="modal">Fermer</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>


		

        <!-- Modal create Template-->
        <div class="modal fade" id="createTemplate" tabindex="-1" role="dialog" aria-labelledby="nodeDetail">
            <div class="modal-dialog" role="document">
                <div class="modal-content">
                    <div class="modal-header">
                        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true"></span></button>
                        <center><h2 class="modal-title" >Create template</h2></center>
                    </div>
                    <form method="post" action="{% url 'createTemplate:templateForm'%}">
                        {% csrf_token %}
                    <div class="modal-body" id="detailTemplate">
                        <a href="#" onclick="add()">Add a node</a>
                            <div class="form-group row">
                                <label for="inputName" style="padding-top: 5px"  class="col-sm-3 col-form-label">Template Name :</label>
                                <div class="col-sm-8">
                                  <input required="" type="text" name="templateName" class="form-control" id="inputName" placeholder="Template Name">
                                </div>
                            </div>
                            <table class="table" id="template">
                                <thead>
                                    <tr>
                                        <th scope="col">Node Type</th>
                                        <th scope="col">Number of instances</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td>
                                            <div class="col-sm-3">
                                                <input type="text" readonly style="border:none;" class="form-control-plaintext" name="node1" value="Compute">
                                            </div>
                                        </td>
                                        <td>
                                            <div style="padding-left:0px;" class="col-sm-6 input-group">
                                                <input name="num1" type="number" min="1" class="form-control" id="computeNumber" value=1 placeholder="1">
                                                	
                                            </div>
                                        </td>
                                    </tr>
                                </tbody>
                                </table>
                        
                    </div>
                    <div class="modal-footer">
    	                <button type="submit" class="btn btn-primary">Submit</button>
                        <button type="button" class="btn btn-primary" data-dismiss="modal">Fermer</button>
                    </div>
                    </form>
                </div>
            </div>
        </div>

		<script type="text/javascript">
			function bs_input_file() {
				$(".input-file").before( 
					function() {
						if ( ! $(this).prev().hasClass('input-ghost') ) {
							var element = $("<input type='file' accept='.yaml,.yml' class='input-ghost' style='visibility:hidden; height:0'>");
							element.attr("name",$(this).attr("name"));
							element.change(function(){
								element.next(element).find('input').val((element.val()).split('\\').pop());
							});
							$(this).find("button.btn-choose").click(function(){
								element.click();
							});
							$(this).find("button.btn-reset").click(function(){
								element.val(null);
								$(this).parents(".input-file").find('input').val('');
							});
							$(this).find('input').css("cursor","pointer");
							$(this).find('input').mousedown(function() {
								$(this).parents('.input-file').prev().click();
								return false;
							});
							return element;
						}
					}
				);
			}
			$(function() {
				bs_input_file();
			});
			function myFunction() {
				var x = document.getElementById("myButn");
				var y = document.getElementById("Fichier1");
				var z = document.getElementById("Fichier2");
				if ( (y.value == "") || (z.value == ""))
					alert('You have to select both files!');

			}
			var cpt = 2 ;
            function add()
            {
            	var select ;
        		$.ajax({
					type: "POST",
					url: "{% url 'createTemplate:list'%}",
					dataType: "json",
					traditional: true,
					data: {"query":"listNode"},
					success: function(response) {
						select = 
							'<div class="col-sm-12"><select name="node'+cpt+'" class="form-control">';
						var i = 1;
					    for (var name in response) {
					    	if(i == 1){
					    		select = select +'<option selected="selected" value="'+response[name]+'">'+name+'</option>';
					    		i++;
					    	}else{
					    		select = select +'<option value="'+response[name]+'">'+name+'</option>';
					    	}
					    	
	                    }
	                    select = select +'</select></div>';
	                    var table = document.getElementById("template");
		                var row = table.insertRow();
		                row.id = row.rowIndex ;
		                // Insert new cells (<td> elements) at the 1st and 2nd position of the "new" <tr> element:
		                var cell1 = row.insertCell(0);
		                var cell2 = row.insertCell(1);

		                // Add some text to the new cells:
		                cell1.innerHTML = select ;
		                cell2.innerHTML =
		                    '<div style="padding-left:0px;" class="col-sm-6 entry input-group">\
		                        <input value=1 name="num'+cpt+'" type="number" min="1" class="form-control" id="computeNumber" placeholder="1">\
										<span class="input-group-btn">\
				                            <a href="#" onclick="del('+ row.id +')" ><button class="btn btn-danger btn-add btPers" type="button">\
				                                <span class="glyphicon glyphicon-minus"> \
				                                </span>\
				                            </button></a>\
				                        </span>\
							</div>';
	                    cpt++;
					},
					error: function(response) {
						console.log(response);
					}
				});
            	
            }
            function del(id)
            {
                console.log(id);
                document.getElementById("template").deleteRow(id);
            }
		</script>
	{% endif %}
{% endblock %}